version: '3.8'
services:
  llm-bot:
    build: .
    volumes:
      - ../data:/data
    network_mode: host
    cap_add:
      - NET_RAW
    healthcheck:
      test: curl --fail http://localhost:9998/status || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s